[tool.poetry]
name = "battery-lifetime"
version = "0.1.0"
description = "Battery lifetime prediction using Random Forest and Gradient Boosting models with PSD features"
authors = ["will_tong2001@yahoo.com <will_tong2001@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.0.0"
scikit-learn = "^1.5.1"
xgboost = "^2.1.0"
pandas = "^2.2.2"
matplotlib = "^3.9.1"
shap = "^0.46.0"
scipy = "^1.14.0"
seaborn = "^0.13.2"
keras = "^3.8.0"
tensorflow = "^2.18.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
